name: Bunny CDN Cache Purge

on:
  schedule:
    - cron: '30 7,10,11,12 * * *'  # Runs at 07:30, 10:30, 11:30, 12:30 UTC daily
  workflow_dispatch:

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Bunny CDN Cache
        run: |
          curl -X POST \
            -H "AccessKey: ${{ secrets.BUNNY_API_KEY }}" \
            "https://api.bunny.net/pullzone/${{ secrets.BUNNY_ZONE_ID }}/purgeCache"
